export const CATEGORY_INIT = 'CATEGORY_INIT';
export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_TITLE_SET = "CATEGORY_TITLE_SET";

export const SECTION_TITLE_SET = "SECTION_TITLE_SET";
export const SECTION_INIT = 'SECTION_INIT';
export const SECTION_ADD = 'SECTION_ADD';

export const ORDERING_INIT = 'ORDERING_INIT';
export const ORDERING_SET = 'ORDERING_SET';
export const ORDERING_CATEGORY_ADD = 'ORDERING_CATEGORY_ADD';
export const ORDERING_SECTION_ADD = 'ORDERING_SECTION_ADD';
export const ORDERING_SECTION_CATEGORIES_SET = 'ORDERING_SECTION_CATEGORIES_SET';

export const PERIOD_INIT = 'PERIOD_INIT';
export const PERIOD_SELECT = 'PERIOD_SELECT';

export const CATEGORYBUDGET_INIT = 'CATEGORYBUDGET_INIT';
export const CATEGORYBUDGET_ADD = "CATEGORYBUDGET_ADD";
export const CATEGORYBUDGET_SET = "CATEGORYBUDGET_SET";

